import { ScenarioDefinition } from '@world26/schemas';
import { LIMITS25_TABLE_8_BENCHMARKS } from './limits25.js';

export const BUILTIN_SCENARIOS: ScenarioDefinition[] = [
  // --- 1. World3 Lineage ---
  {
    id: 'world3_bau',
    name: 'World3: Business as Usual (BAU)',
    family: 'world3',
    description: 'Canonical World3 standard run. Persistent growth in industrial output and population until non-renewable resource depletion triggers an investment crisis.',
    parameterOverrides: {},
    policies: [],
    tags: ['World3', 'Canonical', 'Baseline'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.5,
    integrator: 'rk4',
  },
  {
    id: 'world3_bau2',
    name: 'World3: High Resources (BAU2)',
    family: 'world3',
    description: 'Doubled initial endowment of non-renewable resources. Postpones resource constraints, leading to industrial overshoot and pollution crisis.',
    parameterOverrides: { initial_resources: 2.0e12 },
    policies: [],
    tags: ['World3', 'Resources', 'Pollution Crisis'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.5,
    integrator: 'rk4',
  },
  {
    id: 'world3_ct',
    name: 'World3: Comprehensive Technology',
    family: 'world3',
    description: 'High resources combined with pollution control, agricultural yield enhancement, and resource recycling technologies.',
    parameterOverrides: {
      initial_resources: 2.0e12,
      pollution_generation_factor: 0.25,
      resource_technology_factor: 2.0,
      agricultural_technology_factor: 1.6,
    },
    policies: [],
    tags: ['World3', 'Technology', 'Efficiency'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.5,
    integrator: 'rk4',
  },
  {
    id: 'world3_sw',
    name: 'World3: Stabilized World',
    family: 'world3',
    description: 'Deliberate transition to long-term demographic and economic equilibrium through universal family planning and steady-state capital replacement.',
    parameterOverrides: {
      desired_completed_family_size: 2.0,
      birth_control_effectiveness: 1.0,
      industrial_investment_fraction: 0.14,
      pollution_generation_factor: 0.30,
      resource_technology_factor: 2.0,
    },
    policies: [],
    tags: ['World3', 'Stabilization', 'Equilibrium'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.5,
    integrator: 'rk4',
  },

  // --- 2. LIMITS '25 Reference AI Experiment ---
  {
    id: 'limits25_ai_augmented',
    name: 'LIMITS \'25: AI-Augmented World3-03 (Guliyeva et al.)',
    family: 'ai_computing',
    description: 'Exact reproduction of Guliyeva, Bhardwaj, Becker (LIMITS \'25 / arXiv:2510.07634). Models persistent pollution from AI datacenter operational CO2 and e-waste.',
    parameterOverrides: {
      co2_to_persist: 2.3e-4,
      ai_co2_intensity_2020: 0.15,
      ai_ewaste_intensity_2020: 3.5e-4,
      frac_io_ai_2020: 0.013,
      frac_io_ai_2050: 0.06,
      base_ai_efficiency_improvement: 0.25,
      ai_efficiency_slowdown_rate: 0.04,
      ai_ewaste_improvement_rate: 0.03,
    },
    policies: [],
    tags: ['Research Fixture', 'arXiv:2510.07634', 'Pollution'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.5,
    integrator: 'rk4',
    benchmarks: LIMITS25_TABLE_8_BENCHMARKS.map((b) => ({
      year: b.year,
      variable: 'persistent_pollution',
      value: b.ai,
      tolerancePct: 5.0,
      source: 'Guliyeva et al. (LIMITS 25) Table 8',
    })),
  },

  // --- 3. Earth4All Lineage ---
  {
    id: 'earth4all_too_little_too_late',
    name: 'Earth4All: Too Little Too Late',
    family: 'earth4all',
    description: 'Continuation of current economic policies with incremental reforms. Deepens regional inequality, vulnerability to climate shocks, and social tension.',
    parameterOverrides: {
      universal_basic_services_strength: 0.0,
      carbon_tax_usd_per_ton: 20.0,
      clean_energy_target_2050: 0.70,
    },
    policies: [],
    tags: ['Earth4All', 'Current Policy', 'Inequality'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'earth4all_giant_leap',
    name: 'Earth4All: The Giant Leap',
    family: 'earth4all',
    description: 'Transformational five turnarounds: elimination of poverty, reduction of inequality, empowerment of women, food system transformation, and clean energy transition.',
    parameterOverrides: {
      universal_basic_services_strength: 0.85,
      carbon_tax_usd_per_ton: 150.0,
      clean_energy_target_2050: 0.95,
      food_waste_reduction_pct: 0.50,
      circular_economy_mandate: 0.80,
    },
    policies: [],
    tags: ['Earth4All', 'Turnarounds', 'Wellbeing'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },

  // --- 4. Modern AI & Computing Scenarios ---
  {
    id: 'ai_baseline',
    name: 'WORLD//26 Baseline (Calibrated 2026)',
    family: 'ai_computing',
    description: 'Empirically grounded trajectory combining historical data (1900-2025) with current AI scaling, renewable deployment, and climate commitments.',
    parameterOverrides: {},
    policies: [],
    tags: ['Baseline', 'Reference', 'Calibrated'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'ai_rapid_scaling',
    name: 'AI: Rapid Frontier Scaling',
    family: 'ai_computing',
    description: 'Compute capacity expands at 45% annually with high accelerator investment, testing grid limits, copper demand, and cooling water consumption.',
    parameterOverrides: {
      compute_demand_growth_rate: 0.45,
      ai_productivity_elasticity: 0.12,
    },
    policies: [],
    tags: ['AI', 'Scaling', 'Datacenters'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'ai_jevons_rebound',
    name: 'AI: Extreme Jevons Rebound',
    family: 'ai_computing',
    description: 'Hardware efficiency improves rapidly, but cheaper inference costs trigger backfire rebound elasticity, multiplying total energy and material consumption.',
    parameterOverrides: {
      jevons_rebound_factor: 1.6,
      compute_demand_growth_rate: 0.42,
    },
    policies: [],
    tags: ['AI', 'Jevons Rebound', 'Energy'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'ai_circular_economy',
    name: 'AI: Circular Hardware & Lifetime Extension',
    family: 'ai_computing',
    description: 'Mandatory hardware lifetime extension to 6 years, modular accelerator refurbishment, and 80% critical mineral closed-loop recycling.',
    parameterOverrides: {
      hardware_lifetime_years: 6.0,
      circular_economy_mandate: 0.80,
      water_cooling_liters_per_kwh: 0.5,
    },
    policies: [],
    tags: ['AI', 'Circularity', 'Zero Waste'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'ai_productivity_dividend',
    name: 'AI: High Productivity Dividend',
    family: 'ai_computing',
    description: 'AI breakthroughs translate into substantial macroeconomic TFP improvements (+20% efficiency) while clean grid integration mitigates emissions.',
    parameterOverrides: {
      ai_productivity_elasticity: 0.18,
      clean_energy_target_2050: 0.92,
    },
    policies: [],
    tags: ['AI', 'Productivity', 'Economic Surplus'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },

  // --- 5. Energy Scenarios ---
  {
    id: 'energy_rapid_renewables',
    name: 'Energy: Accelerated Clean Transition',
    family: 'energy',
    description: 'Global electric grid achieves 95% clean power by 2045 backed by steep solar/battery learning curves and carbon pricing.',
    parameterOverrides: {
      clean_energy_target_2050: 0.95,
      clean_energy_phase_in_start: 2026.0,
      carbon_tax_usd_per_ton: 120.0,
    },
    policies: [],
    tags: ['Energy', 'Renewables', 'Decarbonization'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'energy_fossil_persistence',
    name: 'Energy: Fossil Fuel Persistence',
    family: 'energy',
    description: 'Slow grid expansion and fossil infrastructure lock-in limit clean electricity to 55% by 2050, accelerating global warming past 2.5°C.',
    parameterOverrides: {
      clean_energy_target_2050: 0.55,
      carbon_tax_usd_per_ton: 0.0,
    },
    policies: [],
    tags: ['Energy', 'Fossil', 'Climate Risk'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },

  // --- 6. Compound Scenarios ---
  {
    id: 'compound_polycrisis',
    name: 'Compound: Planetary Polycrisis',
    family: 'compound',
    description: 'Simultaneous climate extremes, high AI power demand, critical mineral export restrictions, and worsening economic inequality.',
    parameterOverrides: {
      climate_sensitivity_ecs: 4.2,
      compute_demand_growth_rate: 0.40,
      clean_energy_target_2050: 0.65,
      universal_basic_services_strength: 0.0,
    },
    policies: [],
    tags: ['Compound', 'Polycrisis', 'Systemic Stress'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
  {
    id: 'compound_return_boundaries',
    name: 'Compound: Return Inside All Boundaries',
    family: 'compound',
    description: 'Coordinated global transformation: 95% clean electricity, regenerative agriculture with 50% food waste reduction, circular electronics, and universal basic services.',
    parameterOverrides: {
      clean_energy_target_2050: 0.98,
      carbon_tax_usd_per_ton: 180.0,
      food_waste_reduction_pct: 0.55,
      circular_economy_mandate: 0.85,
      universal_basic_services_strength: 0.90,
      hardware_lifetime_years: 5.5,
    },
    policies: [],
    tags: ['Compound', 'Planetary Boundaries', 'Regeneration'],
    modelVersion: '2026.1',
    dataVersion: '2026.1',
    startYear: 1900,
    endYear: 2100,
    timeStep: 0.25,
    integrator: 'rk4',
  },
];

export function getScenarioById(id: string): ScenarioDefinition | undefined {
  return BUILTIN_SCENARIOS.find((s) => s.id === id);
}
