/**
 * Zero-Dependency Jupyter Notebook (.ipynb) Generator for WORLD//26
 * Exports complete, self-contained, reproducible Python code
 * compatible with JupyterLab, VS Code, Google Colab, and Marimo.
 */

export interface JupyterExportOptions {
  scenarioName: string;
  parameters?: Record<string, number>;
}

export function generateJupyterNotebook({
  scenarioName,
  parameters = {}
}: JupyterExportOptions): string {
  const paramsJson = JSON.stringify(parameters, null, 2);

  const notebook = {
    cells: [
      {
        cell_type: "markdown",
        metadata: {},
        source: [
          `# WORLD//26: Planetary Systems Simulation\n`,
          `## Scenario: ${scenarioName}\n`,
          `*Generated by WORLD//26 Open Planetary Systems Simulator (Apache-2.0)*\n`,
          `\n`,
          `> **Disclaimer**: Independent research and scenario-exploration software. `,
          `Not affiliated with or endorsed by the Club of Rome or the original World3/Earth4All authors.\n`,
          `\n`,
          `This notebook contains a complete, self-contained Python numerical solver for the WORLD//26 `,
          `system dynamics model (1900–2100). It requires **zero external pip dependencies** beyond Python's standard library `,
          `(plus \`matplotlib\` for visualization).\n`
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `# Cell 1: Pure Python Simulation Engine (Runge-Kutta 4th Order / Euler)\n`,
          `import math\n`,
          `import json\n`,
          `\n`,
          `# Active Scenario Parameter Overrides\n`,
          `SCENARIO_PARAMS = ${paramsJson}\n`,
          `\n`,
          `DEFAULT_PARAMS = {\n`,
          `    "initial_population": 1.6e9,\n`,
          `    "target_fertility_replacement": 2.1,\n`,
          `    "capital_output_ratio": 3.0,\n`,
          `    "industrial_depreciation_rate": 0.05,\n`,
          `    "baseline_investment_share": 0.22,\n`,
          `    "clean_energy_target_2050": 0.85,\n`,
          `    "climate_sensitivity_ecs": 3.0,\n`,
          `    "compute_demand_growth_rate": 0.35,\n`,
          `    "hardware_lifetime_years": 3.5,\n`,
          `    "datacenter_pue": 1.25,\n`,
          `    "carbon_tax_usd_per_ton": 0.0,\n`,
          `    "food_waste_reduction_pct": 0.0,\n`,
          `    "amoc_collapse_threshold_temp": 2.2,\n`,
          `    "permafrost_release_rate": 0.025,\n`,
          `    "amazon_dieback_threshold_temp": 2.1,\n`,
          `    "sea_level_rise_rate_m_per_c": 0.0035,\n`,
          `}\n`,
          `PARAMS = {**DEFAULT_PARAMS, **SCENARIO_PARAMS}\n`,
          `\n`,
          `class World26SimulatorPy:\n`,
          `    def __init__(self, params=None):\n`,
          `        self.p = params or PARAMS\n`,
          `        self.state = {\n`,
          `            "time": 1900.0,\n`,
          `            "population": 1.6e9,\n`,
          `            "industrial_capital": 8.0e10,\n`,
          `            "industrial_output": 2.6e10,\n`,
          `            "total_energy_demand_ej": 30.0,\n`,
          `            "clean_electricity_share": 0.05,\n`,
          `            "atmospheric_co2_ppm": 295.0,\n`,
          `            "temperature_anomaly": -0.10,\n`,
          `            "ocean_temperature_anomaly": -0.05,\n`,
          `            "installed_compute_eflops": 0.0,\n`,
          `            "ai_electricity_demand_twh": 0.0,\n`,
          `            "food_per_capita": 840.0,\n`,
          `            "human_wellbeing_index": 0.25,\n`,
          `            "amoc_stability_index": 1.0,\n`,
          `            "permafrost_thaw_co2_gt": 0.0,\n`,
          `            "permafrost_cumulative_gt": 0.0,\n`,
          `            "amazon_forest_fraction": 0.95,\n`,
          `            "sea_level_rise_m": 0.0,\n`,
          `        }\n`,
          `\n`,
          `    def step(self, dt=0.5):\n`,
          `        s = self.state\n`,
          `        t = s["time"]\n`,
          `        p = max(1.0, s["population"])\n`,
          `\n`,
          `        # AI Computing Sector\n`,
          `        if t >= 2015.0:\n`,
          `            growth = self.p.get("compute_demand_growth_rate", 0.35)\n`,
          `            curr = max(0.001, s["installed_compute_eflops"])\n`,
          `            d_compute = curr * growth - (curr / self.p.get("hardware_lifetime_years", 3.5))\n`,
          `            s["installed_compute_eflops"] = max(0.0, s["installed_compute_eflops"] + d_compute * dt)\n`,
          `            eff = 0.05 * (1.18 ** max(0.0, t - 2020.0))\n`,
          `            pwr_gw = (s["installed_compute_eflops"] * 1000.0 / max(0.01, eff)) * 1e-3\n`,
          `            s["ai_electricity_demand_twh"] = pwr_gw * 8.76 * self.p.get("datacenter_pue", 1.25)\n`,
          `\n`,
          `        # Energy & Transition\n`,
          `        s["total_energy_demand_ej"] = max(30.0, 30.0 + (p / 1e9 - 1.6) * 55.0)\n`,
          `        if t >= 2026.0:\n`,
          `            target = self.p.get("clean_energy_target_2050", 0.85)\n`,
          `            trans_rate = (target - s["clean_electricity_share"]) / max(1.0, 2050.0 - t + 10.0)\n`,
          `            s["clean_electricity_share"] = min(0.99, max(0.05, s["clean_electricity_share"] + trans_rate * dt))\n`,
          `\n`,
          `        # Climate & Earth System Tipping Points\n`,
          `        fossil_co2 = s["total_energy_demand_ej"] * (1.0 - s["clean_electricity_share"] * 0.5) * 0.068\n`,
          `        excess_w = max(0.0, s["temperature_anomaly"] - 1.5)\n`,
          `        s["permafrost_thaw_co2_gt"] = min(10.0, (excess_w ** 2) * self.p.get("permafrost_release_rate", 0.025) * 6.0) if excess_w > 0 else 0.0\n`,
          `        s["permafrost_cumulative_gt"] += s["permafrost_thaw_co2_gt"] * dt\n`,
          `        tot_co2 = fossil_co2 + s["permafrost_thaw_co2_gt"] + max(0.5, 3.5 * (1.0 - max(0, t - 1960.0) / 100.0))\n`,
          `\n`,
          `        amoc_s = max(0.0, s["temperature_anomaly"] / self.p.get("amoc_collapse_threshold_temp", 2.2))\n`,
          `        s["amoc_stability_index"] = max(0.0, min(1.0, 1.0 / (1.0 + math.exp(7.0 * (amoc_s - 0.85)))))\n`,
          `        s["sea_level_rise_m"] += max(0.0, s["temperature_anomaly"]) * self.p.get("sea_level_rise_rate_m_per_c", 0.0035) * dt\n`,
          `\n`,
          `        d_co2 = (tot_co2 * 0.48 / (0.70 + 0.30 * s["amoc_stability_index"])) / 3.8\n`,
          `        s["atmospheric_co2_ppm"] = max(200.0, s["atmospheric_co2_ppm"] + d_co2 * dt)\n`,
          `        rad_forcing = 5.35 * math.log(s["atmospheric_co2_ppm"] / 280.0)\n`,
          `        lambda_fb = 3.71 / self.p.get("climate_sensitivity_ecs", 3.0)\n`,
          `        d_temp = (rad_forcing - lambda_fb * s["temperature_anomaly"] - 0.73 * (s["temperature_anomaly"] - s["ocean_temperature_anomaly"])) / 5.0\n`,
          `        d_ocean_t = (0.73 * (s["temperature_anomaly"] - s["ocean_temperature_anomaly"])) / 100.0\n`,
          `        s["temperature_anomaly"] += d_temp * dt\n`,
          `        s["ocean_temperature_anomaly"] += d_ocean_t * dt\n`,
          `\n`,
          `        # Demography\n`,
          `        birth_rate = p * 0.035 * max(0.5, 1.0 - (t - 1900.0) / 300.0)\n`,
          `        death_rate = p / max(30.0, 35.0 + 35.0 * min(1.2, max(0.4, s["food_per_capita"] / 350.0)))\n`,
          `        s["population"] = max(1.0, s["population"] + (birth_rate - death_rate) * dt)\n`,
          `        s["human_wellbeing_index"] = max(0.1, min(1.0, 0.4 + (s["food_per_capita"] / 1000.0) * 0.3 - max(0.0, s["temperature_anomaly"] - 1.5) * 0.2))\n`,
          `\n`,
          `        s["time"] += dt\n`,
          `        return dict(s)\n`,
          `\n`,
          `print("✓ WORLD//26 Python Simulator initialized.")\n`
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `# Cell 2: Run Full Simulation from 1900 to 2100\n`,
          `sim = World26SimulatorPy()\n`,
          `history = []\n`,
          `while sim.state["time"] <= 2100.0:\n`,
          `    history.append(sim.step(dt=0.5))\n`,
          `\n`,
          `times = [h["time"] for h in history]\n`,
          `pop_billions = [h["population"] / 1e9 for h in history]\n`,
          `co2_ppm = [h["atmospheric_co2_ppm"] for h in history]\n`,
          `temp_anom = [h["temperature_anomaly"] for h in history]\n`,
          `compute_eflops = [h["installed_compute_eflops"] for h in history]\n`,
          `amoc_index = [h["amoc_stability_index"] for h in history]\n`,
          `\n`,
          `print(f"Simulation completed: {len(history)} steps.")\n`,
          `print(f"2026: Temp={temp_anom[252]:.2f}°C, CO2={co2_ppm[252]:.1f} ppm, Pop={pop_billions[252]:.2f}B")\n`,
          `print(f"2100: Temp={temp_anom[-1]:.2f}°C, CO2={co2_ppm[-1]:.1f} ppm, Pop={pop_billions[-1]:.2f}B, AMOC={amoc_index[-1]:.2f}")\n`
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          `# Cell 3: Plot Trajectories using Matplotlib\n`,
          `import matplotlib.pyplot as plt\n`,
          `\n`,
          `fig, axes = plt.subplots(2, 2, figsize=(14, 9))\n`,
          `plt.style.use('dark_background') if 'dark_background' in plt.style.available else None\n`,
          `\n`,
          `# Population\n`,
          `axes[0, 0].plot(times, pop_billions, color='#38bdf8', lw=2)\n`,
          `axes[0, 0].set_title("Global Population (Billion persons)")\n`,
          `axes[0, 0].grid(True, alpha=0.2)\n`,
          `\n`,
          `# Temperature & CO2\n`,
          `axes[0, 1].plot(times, temp_anom, color='#f43f5e', lw=2, label="Temperature Anomaly (°C)")\n`,
          `axes[0, 1].axhline(1.5, color='#fbbf24', ls='--', alpha=0.7, label="+1.5°C Threshold")\n`,
          `axes[0, 1].set_title("Global Mean Surface Warming")\n`,
          `axes[0, 1].legend()\n`,
          `axes[0, 1].grid(True, alpha=0.2)\n`,
          `\n`,
          `# AI Compute Capacity\n`,
          `axes[1, 0].plot(times, compute_eflops, color='#c084fc', lw=2)\n`,
          `axes[1, 0].set_xlim(2015, 2100)\n`,
          `axes[1, 0].set_title("Installed AI Compute Capacity (EFLOP/s)")\n`,
          `axes[1, 0].grid(True, alpha=0.2)\n`,
          `\n`,
          `# Earth System Tipping: AMOC Stability\n`,
          `axes[1, 1].plot(times, amoc_index, color='#34d399', lw=2, label="AMOC Stability (1=stable)")\n`,
          `axes[1, 1].set_title("Atlantic Meridional Overturning Circulation (AMOC)")\n`,
          `axes[1, 1].set_ylim(0, 1.05)\n`,
          `axes[1, 1].legend()\n`,
          `axes[1, 1].grid(True, alpha=0.2)\n`,
          `\n`,
          `plt.tight_layout()\n`,
          `plt.show()\n`
        ]
      }
    ],
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        name: "python",
        version: "3.11"
      }
    },
    nbformat: 4,
    nbformat_minor: 2
  };

  return JSON.stringify(notebook, null, 2);
}

/**
 * Triggers a browser download of the Jupyter notebook.
 */
export function downloadJupyterNotebook(scenarioName: string, parameters?: Record<string, number>): void {
  const content = generateJupyterNotebook({ scenarioName, parameters });
  const blob = new Blob([content], { type: 'application/x-ipynb+json;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const cleanName = scenarioName.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  a.download = `world26_${cleanName}.ipynb`;
  a.click();
  URL.revokeObjectURL(url);
}
